common: &common
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: pgbike
  password:

production:
  <<: *common
  databaes: sfbike_production
development:
  <<: *common
  database: sfbike_development

test:
  <<: *common
  database: sfbike_test
